### ISSUE TITLE
Can't validate in the presence of omitted `Maybe` fields.

### ISSUE THREAD

**Issue by mdorman** [ocharles/json-assertions#1]
I do not believe that `Test.JSON.Assertions` can be used in situations where you have set your `toJSON` instance to elide `Maybe` fields that have a value of `Nothing`.

This is easily achievable using the `Aeson` support for `GHC.Generics` and deriving your instance thusly:

``` haskell
instance ToJSON Foo where
  toJSON = genericToJSON defaultOptions {omitNothingFields = True}
```

Obviously, opinions might differ on whether this is an appropriate encoding, but it seems like it would be a nice thing if `Test.JSON.Assertions` supported it.

I was going to take a stab at implementing it, though I'm enough of a novice that it might take me a little while, so if you feel motivated, please don't hold back :)

My (very tentative) plan would be to add an `optionalKey`, err, descriptor?, that would be much like the existing `key`, but would basically skip the check for a `Nothing` result that the current `key` does, and let it continue on through.

Does that sound reasonable?  If I produce a patch, would you be willing to add that functionality?

**Comment by mitchellwrosen** [comment]
Hi @ocharles, are you still interested in this feature? I randomly stumbled across your indexed free monads blog post today :)

**Comment by ocharles** [comment]
I'm certainly not not interested, put it that way! :)

I'll try and find some time tomorrow to revisit this and see if I can move this forward.

**Comment by ocharles** [comment]
I am no longer using this library, so I'm afraid I'm going to have to abandon it. If anyone fixes this a PR is welcome. Likewise, if anyone wants to maintain this package, please drop me a line. Sorry to have to close.
